### ISSUE TITLE
Split input label maps w metadata

### ISSUE THREAD

**Issue by kaitj** [khanlab/labelmerge#4]
### Tasks 
- [x] Use `nibabel` to read labelmap
- [x] Add Python script to split labels into binary volumes
  - [x] Output as BIDS label masks
- [x] Fix `dtype` for memory purposes 
- [x] Add in label descriptions from .tsv 
- [x] Determine naming scheme
  - [x] Aggregation output rule
